language: android
dist: trusty
android:
  components:
    - build-tools-29.0.0

    - android-29

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository